version: '3'
services:
  model-gcn:
    hostname: model-gcn
    volumes:
      - .:/workspace
    build:
      context: .
      dockerfile: Dockerfile
  gnn-collection:
    hostname: gnn-colelct
    volumes:
      - .:/workspace
    build:
      context: gnn/collection 
      dockerfile: Dockerfile

