name: Build LaTeX document
on:
  - pull_request
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: gnn.tex
          args: '-pdf -file-line-error -interaction=nonstopmode -shell-escape'
          working_directory: paper
      - name: Compile LaTeX slides deck
        uses: xu-cheng/latex-action@v2
        with:
          root_file: gnn-pres.tex
          args: '-pdf -file-line-error -interaction=nonstopmode -shell-escape'
          working_directory: presentation

